project_id = "req"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/confirm",
  "http://localhost:3000/reset-password",
  "https://req-sand.vercel.app/auth/callback",
  "https://req-sand.vercel.app/auth/confirm",
  "https://req-sand.vercel.app/reset-password",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
